### ISSUE TITLE
L1 screen PhonePe Not Show And Google Pay not working Error Oops,something went wrong .

### ISSUE THREAD

**Issue by krishna2917** [payu-intrepos/PayUCheckoutPro-Android#12]
Problem Statement - Show on L1 screen PhonePe Not Show And Google Pay not working Error Oops,something went wrong .
Problem faced on which server - production .
![IMG_20210807_141348](https://user-images.githubusercontent.com/62599120/128603372-a0bae14c-471c-4afe-a313-8cbbdf1749fc.jpg)
![IMG_20210807_141217](https://user-images.githubusercontent.com/62599120/128603386-eee1f239-e2e6-459a-9ea1-9a4e047c8ee1.jpg)

**Comment by Rahul-Hooda** [comment]
@krishna2917 - Please drop a mail at mobile.integration@payu.in with all the details for a quick help.
