### ISSUE TITLE
how to call enforce_paymethod payment in payu checkout pro android

### ISSUE THREAD

**Issue by ChetanPatelSS** [payu-intrepos/PayUCheckoutPro-Android#13]
how can we call direct payment options like open credit/debit card payment or wallet payment direct? 

![image](https://user-images.githubusercontent.com/76802990/128877160-1ec0bc7e-3750-469c-a16d-3baa918de058.png)

**Comment by Rahul-Hooda** [comment]
@ChetanPatelSS - CheckoutPro SDK doesn't have this currently but will be picked in future releases.
