### ISSUE TITLE
Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by shrikantingole** [payu-intrepos/PayUCheckoutPro-Android#2]
when i used https://www.payumoney.com/merchant-dashboard/#/integration
credentails not workign getting me errror Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

please help me from where should i get credentials for this project 
PayUCheckoutPro-Android

**Comment by himgupta229** [comment]
Kindly reach out to mobile.integration@payu.in

**Comment by SlickSlime** [comment]
We're also facing the same issue. The sample is working fine when using the default Key/Salt. But when we set our own Key/Salt on either Test and Production environment we are getting `Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject` error.

**Comment by SlickSlime** [comment]
@shrikantingole Did you found any solution to this issue?

**Comment by sabin19** [comment]
Still it is not working

**Comment by Rahul-Hooda** [comment]
PayUmoney Credentials will not work on CheckoutPro SDK. Please drop a mail to mobile.integration@payu.in to get relevant help regarding this.

**Comment by Deepakkast** [comment]
Just set 

builder.setIsProduction(true)
