### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'com.payu.base.models.BaseConfig com.payu.base.models.BaseApiLayer.getConfig()'

### ISSUE THREAD

**Issue by Thamizhan** [payu-intrepos/PayUCheckoutPro-Android#42]
We are getting random crashes from our live users.

The logs shows something like this NullPointerException: Attempt to invoke virtual method 'com.payu.base.models.BaseConfig com.payu.base.models.BaseApiLayer.getConfig()'

Attached full log file.

Versions used
in.payu:payu-checkout-pro: 2.0.9
in.payu:olamoney: 1.2.2
in.payu:phonepe-intent: 1.7.2
in.payu:payu-gpay: 1.5.3

[gxl.shyaway_issue_123968da1756ca84dc011d06d01a3e11_crash_session_6461A87A00430001337938381CFEC045_DNE_0_v2_stacktrace.txt](https://github.com/payu-intrepos/PayUCheckoutPro-Android/files/11474260/gxl.shyaway_issue_123968da1756ca84dc011d06d01a3e11_crash_session_6461A87A00430001337938381CFEC045_DNE_0_v2_stacktrace.txt)

**Comment by shahfaizalc** [comment]
this issue has been resolved in.  in.payu:payu-checkout-pro: 2.0.15. I request you to update to our latest versions


in.payu:payu-checkout-pro: 2.0.19
in.payu:olamoney: 1.2.4
in.payu:phonepe-intent: 1.7.4
in.payu:payu-gpay: 1.5.4
