### ISSUE TITLE
Manifest merger failed : Attribute application@usesCleartextTraffic value=(true)

### ISSUE THREAD

**Issue by goswamiji0** [payu-intrepos/PayUCheckoutPro-Android#5]
Getting below error 
Manifest merger failed : Attribute application@usesCleartextTraffic value=(true) from AndroidManifest.xml:21:9-44
	is also present at [com.payu.custombrowser:payu-custom-browser:7.6.3] AndroidManifest.xml:17:18-54 value=(false).
	Suggestion: add 'tools:replace="android:usesCleartextTraffic"' to <application> element at AndroidManifest.xml:12:5-64:19 to override.

But i also want to use android:usesCleartextTraffic=true in my application

**Comment by Rahul-Hooda** [comment]
@goswamiji0 - You can override it with tools:replace as mentioned above but PayU doesn't recommend to use http urls for Security concerns and doesn't recommend to set it to true. .
