### ISSUE TITLE
Your app(s) are vulnerable to Intent Redirection

### ISSUE THREAD

**Issue by siddharthvnk1008** [payu-intrepos/PayUCheckoutPro-Android#8]
Hi Team,
This is a serious issue after integrating your SDK google  play console is reposting this issue please let us know any solution for this issue
Your app(s) are vulnerable to Intent Redirection. To address this issue, follow the steps in this Google Help Center article.

androidx.activity.ComponentActivity.startActivityForResult
am using this versionimplementation 'in.payu:payu-checkout-pro:1.5.0'

**Comment by daryljodanny** [comment]
Getting the same issue for 'in.payu:payu-checkout-pro:1.5.0'

**Comment by Rahul-Hooda** [comment]
@daryljodanny - Please use our latest version 'in.payu:payu-checkout-pro:1.7.0'
